2025-05-23 13:49:31 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 13:49:31 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 13:55:01 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 13:55:01 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 13:56:04 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 13:56:04 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:01:44 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:01:44 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:03:09 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:03:09 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:04:09 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:04:09 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:06:27 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:06:27 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:15:23 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:15:23 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:22:04 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:22:04 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:23:15 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:23:15 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:23:50 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:23:50 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:24:12 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:24:12 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:24:53 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:24:53 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:26:27 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:26:27 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:29:59 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:29:59 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:32:18 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:32:18 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:36:30 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:36:30 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:40:22 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:40:22 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:40:22 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 14:40:22 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 14:40:22.809112 (cli.py:195)
2025-05-23 14:40:22 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 14:40:22 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 14:40:22 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 14:40:22 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 14:40:23 [DEBUG   ] open file: /Users/kraus-d/projects/ldndctools-kraus/data/ne_50m_admin_0_countries.zip (local.py:375)
2025-05-23 14:55:54 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:55:54 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:55:56 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 14:55:56 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 14:55:56.758994 (cli.py:195)
2025-05-23 14:55:56 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 14:55:56 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 14:55:56 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 14:55:56 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 14:55:58 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 14:55:58 [DEBUG   ] https://github.com/GraceBarbacias/sources/raw/main/ne_50m_admin_0_countries.zip (http.py:244)
2025-05-23 14:56:00 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 14:56:00 [DEBUG   ] Copying ldndcdata/GLOBAL_WISESOIL_S1_LR.nc to local cache (cached.py:873)
2025-05-23 14:56:00 [DEBUG   ] Get directory listing page for ldndcdata/GLOBAL_WISESOIL_S1_LR.nc (core.py:385)
2025-05-23 14:56:00 [DEBUG   ] Starting new HTTPS connection (1): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:56:06 [DEBUG   ] Starting new HTTPS connection (2): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:56:13 [DEBUG   ] Starting new HTTPS connection (3): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:56:21 [DEBUG   ] Starting new HTTPS connection (4): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:56:27 [DEBUG   ] Starting new HTTPS connection (5): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:57:48 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 14:57:48 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 14:57:48 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 14:57:48 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 14:57:48.756782 (cli.py:195)
2025-05-23 14:57:48 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 14:57:48 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 14:57:48 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 14:57:48 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 14:57:48 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 14:57:49 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 14:57:49 [DEBUG   ] Copying ldndcdata/GLOBAL_WISESOIL_S1_LR.nc to local cache (cached.py:873)
2025-05-23 14:57:49 [DEBUG   ] Get directory listing page for ldndcdata/GLOBAL_WISESOIL_S1_LR.nc (core.py:385)
2025-05-23 14:57:49 [DEBUG   ] Starting new HTTPS connection (1): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:57:54 [DEBUG   ] Starting new HTTPS connection (2): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:58:00 [DEBUG   ] Starting new HTTPS connection (3): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:58:08 [DEBUG   ] Starting new HTTPS connection (4): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 14:58:18 [DEBUG   ] Starting new HTTPS connection (5): s3.imk-ifu.kit.edu:443 (connectionpool.py:1049)
2025-05-23 15:08:15 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:08:15 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:08:15 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:08:15 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:08:15.857906 (cli.py:195)
2025-05-23 15:08:15 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:08:15 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:08:15 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:08:15 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:08:16 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:08:16 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:08:16 [DEBUG   ] Copying ldndcdata/GLOBAL_WISESOIL_S1_LR.nc to local cache (cached.py:873)
2025-05-23 15:08:16 [DEBUG   ] Get directory listing page for ldndcdata/GLOBAL_WISESOIL_S1_LR.nc (core.py:385)
2025-05-23 15:08:16 [DEBUG   ] Starting new HTTPS connection (1): s3.imk-ifu.kit.edu:10443 (connectionpool.py:1049)
2025-05-23 15:08:17 [DEBUG   ] https://s3.imk-ifu.kit.edu:10443 "GET /ldndcdata?list-type=2&prefix=GLOBAL_WISESOIL_S1_LR.nc%2F&delimiter=%2F&encoding-type=url HTTP/1.1" 200 321 (connectionpool.py:544)
2025-05-23 15:08:17 [DEBUG   ] Get directory listing page for ldndcdata (core.py:385)
2025-05-23 15:08:17 [DEBUG   ] https://s3.imk-ifu.kit.edu:10443 "GET /ldndcdata?list-type=2&prefix=&delimiter=%2F&encoding-type=url HTTP/1.1" 200 1255 (connectionpool.py:544)
2025-05-23 15:08:17 [DEBUG   ] Fetch: ldndcdata/GLOBAL_WISESOIL_S1_LR.nc, 0-6898815 (core.py:1330)
2025-05-23 15:08:17 [DEBUG   ] https://s3.imk-ifu.kit.edu:10443 "GET /ldndcdata/GLOBAL_WISESOIL_S1_LR.nc HTTP/1.1" 206 6898815 (connectionpool.py:544)
2025-05-23 15:08:19 [DEBUG   ] <File-like object S3FileSystem, ldndcdata/GLOBAL_WISESOIL_S1_LR.nc> read: 0 - 4194304  , bytes: 0 hits, 1 misses, 6898815 total requested bytes (spec.py:2113)
2025-05-23 15:08:19 [DEBUG   ] <File-like object S3FileSystem, ldndcdata/GLOBAL_WISESOIL_S1_LR.nc> read: 4194304 - 8388608  , bytes: 0 hits, 2 misses, 6898815 total requested bytes (spec.py:2113)
2025-05-23 15:08:19 [DEBUG   ] <File-like object S3FileSystem, ldndcdata/GLOBAL_WISESOIL_S1_LR.nc> read: 6898815 - 11093119  , bytes: 0 hits, 2 misses, 6898815 total requested bytes (spec.py:2113)
2025-05-23 15:10:16 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:10:16 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:10:17 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:10:17 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:10:17.249585 (cli.py:195)
2025-05-23 15:10:17 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:10:17 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:10:17 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:10:17 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:10:17 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:10:17 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:12:48 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:12:48 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:12:53 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:12:53 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:12:53.091563 (cli.py:195)
2025-05-23 15:12:53 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:12:53 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:12:53 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:12:53 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:12:53 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:12:54 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:14:46 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:14:46 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:14:46 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:14:46 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:14:46.937786 (cli.py:195)
2025-05-23 15:14:46 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:14:46 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:14:46 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:14:46 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:14:47 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:14:47 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:16:28 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:16:28 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:16:29 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:16:29 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:16:29.223182 (cli.py:195)
2025-05-23 15:16:29 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:16:29 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:16:29 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:16:29 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:16:29 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:16:29 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:17:15 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:17:15 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:17:15 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:17:15 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:17:15.543094 (cli.py:195)
2025-05-23 15:17:15 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:17:15 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:17:15 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:17:15 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:17:15 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:17:15 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:19:11 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:19:11 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:19:11 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:19:11 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:19:11.298512 (cli.py:195)
2025-05-23 15:19:11 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:19:11 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:19:11 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:19:11 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:19:11 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:19:11 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:19:46 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:19:46 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:19:46 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:19:46 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:19:46.365151 (cli.py:195)
2025-05-23 15:19:46 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:19:46 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:19:46 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:19:46 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:19:46 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:19:46 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:24:01 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:24:01 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:24:01 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:24:01 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:24:01.491593 (cli.py:195)
2025-05-23 15:24:01 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:24:01 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:24:01 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:24:01 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:24:01 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:24:27 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:24:27 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:24:28 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:24:28 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:24:28.153276 (cli.py:195)
2025-05-23 15:24:28 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:24:28 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:24:28 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:24:28 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:24:28 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:26:03 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:26:03 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:26:04 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:26:04 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:26:04.628184 (cli.py:195)
2025-05-23 15:26:04 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:26:04 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:26:04 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:26:04 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:26:04 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:26:04 [DEBUG   ] https://github.com/GraceBarbacias/sources/raw/main/ne_50m_admin_0_countries.zip' (http.py:244)
2025-05-23 15:27:16 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:27:16 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:27:16 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:27:16 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:27:16.659512 (cli.py:195)
2025-05-23 15:27:16 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:27:16 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:27:16 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:27:16 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:27:16 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:27:16 [DEBUG   ] https://github.com/GraceBarbacias/sources/raw/main/ne_50m_admin_0_countries.zip' (http.py:244)
2025-05-23 15:27:32 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:27:32 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:27:32 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:27:32 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:27:32.681151 (cli.py:195)
2025-05-23 15:27:32 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:27:32 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:27:32 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:27:32 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:27:32 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:27:32 [DEBUG   ] https://github.com/GraceBarbacias/sources/raw/main/ne_50m_admin_0_countries.zip' (http.py:244)
2025-05-23 15:28:18 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:28:18 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:28:19 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:28:19 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:28:19.076389 (cli.py:195)
2025-05-23 15:28:19 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:28:19 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:28:19 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:28:19 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:28:19 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:28:19 [DEBUG   ] https://github.com/GraceBarbacias/sources/raw/main/ne_50m_admin_0_countries.zip' (http.py:244)
2025-05-23 15:28:49 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:28:49 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:28:49 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:28:49 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:28:49.465547 (cli.py:195)
2025-05-23 15:28:49 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:28:49 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:28:49 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:28:49 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:28:49 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:28:49 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:28:49 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:28:50 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:30:53 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:30:53 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:30:53 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:30:53 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:30:53.390651 (cli.py:195)
2025-05-23 15:30:53 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:30:53 [INFO    ] Soil resolution: LR Low-res [0.5°] (dlsc.py:115)
2025-05-23 15:30:53 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:30:53 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:30:53 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:30:53 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:30:53 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:30:54 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:30:57 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:30:57 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:30:57 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:30:57 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:31:01 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 15:31:01 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 15:31:01 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 15:31:02 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x151701090> (env.py:284)
2025-05-23 15:31:02 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 15:31:02 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:31:02 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x15171eda0> created (env.py:336)
2025-05-23 15:31:02 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x15171eda0>. (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x151701090> (env.py:308)
2025-05-23 15:31:02 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x15171c160> (env.py:284)
2025-05-23 15:31:02 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x15171eda0> options (env.py:346)
2025-05-23 15:31:02 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x15171c160> (env.py:308)
2025-05-23 15:31:02 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 15:31:02 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x15171c160> (env.py:312)
2025-05-23 15:31:02 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x15171eda0> options (env.py:373)
2025-05-23 15:31:02 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x15171eda0>. (env.py:374)
2025-05-23 15:31:02 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:31:02 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x15171eda0> created (env.py:336)
2025-05-23 15:31:02 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x15171eda0>. (env.py:338)
2025-05-23 15:31:02 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x15171c160> (env.py:325)
2025-05-23 15:31:02 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x151701090> (env.py:312)
2025-05-23 15:31:02 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x15171eda0> options (env.py:373)
2025-05-23 15:31:02 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x15171eda0>. (env.py:374)
2025-05-23 15:31:02 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 15:31:02 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x151701090> (env.py:325)
2025-05-23 15:37:15 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:37:15 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:37:15 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:37:15 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:37:15.677230 (cli.py:195)
2025-05-23 15:37:15 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:37:15 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 15:37:15 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:37:15 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:37:15 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:37:15 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:37:15 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:37:16 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:37:18 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:37:18 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:37:18 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:37:18 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:37:20 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 15:37:20 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 15:37:20 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 15:37:21 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x12e05d660> (env.py:284)
2025-05-23 15:37:21 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 15:37:21 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:37:21 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x12e07b010> created (env.py:336)
2025-05-23 15:37:21 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x12e07b010>. (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x12e05d660> (env.py:308)
2025-05-23 15:37:21 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x12e07a350> (env.py:284)
2025-05-23 15:37:21 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x12e07b010> options (env.py:346)
2025-05-23 15:37:21 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x12e07a350> (env.py:308)
2025-05-23 15:37:21 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 15:37:21 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x12e07a350> (env.py:312)
2025-05-23 15:37:21 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x12e07b010> options (env.py:373)
2025-05-23 15:37:21 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x12e07b010>. (env.py:374)
2025-05-23 15:37:21 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:37:21 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x12e07b010> created (env.py:336)
2025-05-23 15:37:21 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x12e07b010>. (env.py:338)
2025-05-23 15:37:21 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x12e07a350> (env.py:325)
2025-05-23 15:37:21 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x12e05d660> (env.py:312)
2025-05-23 15:37:21 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x12e07b010> options (env.py:373)
2025-05-23 15:37:21 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x12e07b010>. (env.py:374)
2025-05-23 15:37:21 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 15:37:21 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x12e05d660> (env.py:325)
2025-05-23 15:38:44 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:38:44 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:38:44 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:38:44 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:38:44.339849 (cli.py:195)
2025-05-23 15:38:44 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:38:44 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 15:38:44 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:38:44 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:38:44 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:38:44 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:38:44 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:38:45 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:38:46 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:38:46 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:38:46 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:38:46 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:38:49 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 15:38:49 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 15:38:49 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 15:38:50 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x15461d090> (env.py:284)
2025-05-23 15:38:50 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 15:38:50 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:38:50 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x15463ada0> created (env.py:336)
2025-05-23 15:38:50 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x15463ada0>. (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x15461d090> (env.py:308)
2025-05-23 15:38:50 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x154638160> (env.py:284)
2025-05-23 15:38:50 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x15463ada0> options (env.py:346)
2025-05-23 15:38:50 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x154638160> (env.py:308)
2025-05-23 15:38:50 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 15:38:50 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x154638160> (env.py:312)
2025-05-23 15:38:50 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x15463ada0> options (env.py:373)
2025-05-23 15:38:50 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x15463ada0>. (env.py:374)
2025-05-23 15:38:50 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:38:50 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x15463ada0> created (env.py:336)
2025-05-23 15:38:50 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x15463ada0>. (env.py:338)
2025-05-23 15:38:50 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x154638160> (env.py:325)
2025-05-23 15:38:50 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x15461d090> (env.py:312)
2025-05-23 15:38:50 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x15463ada0> options (env.py:373)
2025-05-23 15:38:50 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x15463ada0>. (env.py:374)
2025-05-23 15:38:50 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 15:38:50 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x15461d090> (env.py:325)
2025-05-23 15:39:16 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:39:16 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:39:16 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:39:16 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:39:16.398766 (cli.py:195)
2025-05-23 15:39:16 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:39:16 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 15:39:16 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:39:16 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:39:16 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:39:16 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:39:16 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:39:17 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:39:18 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:39:18 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:39:18 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:39:18 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:39:21 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 15:39:21 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 15:39:21 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 15:39:22 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x13f5774c0> (env.py:284)
2025-05-23 15:39:22 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 15:39:22 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:39:22 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x13f5975b0> created (env.py:336)
2025-05-23 15:39:22 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x13f5975b0>. (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x13f5774c0> (env.py:308)
2025-05-23 15:39:22 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x13f597e50> (env.py:284)
2025-05-23 15:39:22 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x13f5975b0> options (env.py:346)
2025-05-23 15:39:22 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x13f597e50> (env.py:308)
2025-05-23 15:39:22 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 15:39:22 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x13f597e50> (env.py:312)
2025-05-23 15:39:22 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x13f5975b0> options (env.py:373)
2025-05-23 15:39:22 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x13f5975b0>. (env.py:374)
2025-05-23 15:39:22 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:39:22 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x13f5975b0> created (env.py:336)
2025-05-23 15:39:22 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x13f5975b0>. (env.py:338)
2025-05-23 15:39:22 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x13f597e50> (env.py:325)
2025-05-23 15:39:22 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x13f5774c0> (env.py:312)
2025-05-23 15:39:22 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x13f5975b0> options (env.py:373)
2025-05-23 15:39:22 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x13f5975b0>. (env.py:374)
2025-05-23 15:39:22 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 15:39:22 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x13f5774c0> (env.py:325)
2025-05-23 15:40:33 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:40:33 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:40:33 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:40:33 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:40:33.316355 (cli.py:195)
2025-05-23 15:40:33 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:40:33 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 15:40:33 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:40:33 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:40:33 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:40:33 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:40:33 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:40:34 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:40:35 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:40:35 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:40:35 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:40:35 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:40:38 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 15:40:38 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 15:40:38 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 15:40:39 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x15333f4c0> (env.py:284)
2025-05-23 15:40:39 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 15:40:39 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:40:39 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x15335b5b0> created (env.py:336)
2025-05-23 15:40:39 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x15335b5b0>. (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x15333f4c0> (env.py:308)
2025-05-23 15:40:39 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x15335be50> (env.py:284)
2025-05-23 15:40:39 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x15335b5b0> options (env.py:346)
2025-05-23 15:40:39 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x15335be50> (env.py:308)
2025-05-23 15:40:39 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 15:40:39 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x15335be50> (env.py:312)
2025-05-23 15:40:39 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x15335b5b0> options (env.py:373)
2025-05-23 15:40:39 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x15335b5b0>. (env.py:374)
2025-05-23 15:40:39 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:40:39 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x15335b5b0> created (env.py:336)
2025-05-23 15:40:39 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x15335b5b0>. (env.py:338)
2025-05-23 15:40:39 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x15335be50> (env.py:325)
2025-05-23 15:40:39 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x15333f4c0> (env.py:312)
2025-05-23 15:40:39 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x15335b5b0> options (env.py:373)
2025-05-23 15:40:39 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x15335b5b0>. (env.py:374)
2025-05-23 15:40:39 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 15:40:39 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x15333f4c0> (env.py:325)
2025-05-23 15:42:54 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 15:42:54 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 15:42:55 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 15:42:55 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 15:42:55.968647 (cli.py:195)
2025-05-23 15:42:55 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 15:42:55 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 15:42:55 [INFO    ] Outfile name:    test_out.xml (dlsc.py:116)
2025-05-23 15:42:56 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 15:42:56 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 15:42:56 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 15:42:56 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:42:58 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 15:42:59 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:42:59 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:42:59 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 15:42:59 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 15:43:01 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 15:43:01 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 15:43:01 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 15:43:02 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x144ed1d20> (env.py:284)
2025-05-23 15:43:02 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 15:43:02 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:43:02 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x153f2bd00> created (env.py:336)
2025-05-23 15:43:02 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x153f2bd00>. (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x144ed1d20> (env.py:308)
2025-05-23 15:43:02 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x153f2ad40> (env.py:284)
2025-05-23 15:43:02 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x153f2bd00> options (env.py:346)
2025-05-23 15:43:02 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x153f2ad40> (env.py:308)
2025-05-23 15:43:02 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 15:43:02 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x153f2ad40> (env.py:312)
2025-05-23 15:43:02 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x153f2bd00> options (env.py:373)
2025-05-23 15:43:02 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x153f2bd00>. (env.py:374)
2025-05-23 15:43:02 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 15:43:02 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x153f2bd00> created (env.py:336)
2025-05-23 15:43:02 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x153f2bd00>. (env.py:338)
2025-05-23 15:43:02 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x153f2ad40> (env.py:325)
2025-05-23 15:43:02 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x144ed1d20> (env.py:312)
2025-05-23 15:43:02 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x153f2bd00> options (env.py:373)
2025-05-23 15:43:02 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x153f2bd00>. (env.py:374)
2025-05-23 15:43:02 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 15:43:02 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x144ed1d20> (env.py:325)
2025-05-23 16:08:50 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 16:08:50 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 16:08:51 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 16:08:51 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 16:08:51.931752 (cli.py:195)
2025-05-23 16:08:51 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 16:08:51 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 16:08:51 [INFO    ] Outfile name:    test_out_HR.xml (dlsc.py:116)
2025-05-23 16:08:51 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 16:08:52 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 16:08:53 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 16:08:53 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 16:08:54 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 16:08:55 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 16:08:55 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 16:08:55 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 16:08:55 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 16:08:58 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 16:08:58 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 16:08:58 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 16:08:59 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x16dd25660> (env.py:284)
2025-05-23 16:08:59 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 16:08:59 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 16:08:59 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x16dd43010> created (env.py:336)
2025-05-23 16:08:59 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x16dd43010>. (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x16dd25660> (env.py:308)
2025-05-23 16:08:59 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x16dd42350> (env.py:284)
2025-05-23 16:08:59 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x16dd43010> options (env.py:346)
2025-05-23 16:08:59 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x16dd42350> (env.py:308)
2025-05-23 16:08:59 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 16:08:59 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x16dd42350> (env.py:312)
2025-05-23 16:08:59 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x16dd43010> options (env.py:373)
2025-05-23 16:08:59 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x16dd43010>. (env.py:374)
2025-05-23 16:08:59 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 16:08:59 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x16dd43010> created (env.py:336)
2025-05-23 16:08:59 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x16dd43010>. (env.py:338)
2025-05-23 16:08:59 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x16dd42350> (env.py:325)
2025-05-23 16:08:59 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x16dd25660> (env.py:312)
2025-05-23 16:08:59 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x16dd43010> options (env.py:373)
2025-05-23 16:08:59 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x16dd43010>. (env.py:374)
2025-05-23 16:08:59 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 16:08:59 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x16dd25660> (env.py:325)
2025-05-23 16:53:32 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:660)
2025-05-23 16:53:32 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:685)
2025-05-23 16:53:33 [DEBUG   ] -------------------------------------------------- (cli.py:194)
2025-05-23 16:53:33 [DEBUG   ] ldndctools::dlsc called at: 2025-05-23 16:53:33.754883 (cli.py:195)
2025-05-23 16:53:33 [INFO    ] given:    x1=105.0,y1=28.0,x2=106.0,y2=29.0 (dlsc.py:107)
2025-05-23 16:53:33 [INFO    ] Soil resolution: HR High-res [0.083°] (dlsc.py:115)
2025-05-23 16:53:33 [INFO    ] Outfile name:    test_out_HR.xml (dlsc.py:116)
2025-05-23 16:53:33 [DEBUG   ] open file: /Users/au783075/ldndctools/data/catalog.yml (local.py:375)
2025-05-23 16:53:34 [DEBUG   ] Using selector: KqueueSelector (selector_events.py:54)
2025-05-23 16:53:34 [DEBUG   ] Setting up s3fs instance (core.py:282)
2025-05-23 16:53:34 [DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 16:53:35 [DEBUG   ] Starting new HTTP connection (2): 169.254.169.254:80 (connectionpool.py:241)
2025-05-23 16:53:36 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 16:53:36 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 16:53:36 [DEBUG   ] Creating converter from 7 to 5 (__init__.py:47)
2025-05-23 16:53:36 [DEBUG   ] Creating converter from 5 to 7 (__init__.py:47)
2025-05-23 16:53:39 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:147)
2025-05-23 16:53:39 [INFO    ] Setting bounding box to BoundingBox(x1=105.0, x2=106.0, y1=28.0, y2=29.0) (dlsc.py:149)
2025-05-23 16:53:39 [INFO    ] Using Selector (create_data.py:30)
2025-05-23 16:53:40 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x16cd05090> (env.py:284)
2025-05-23 16:53:40 [DEBUG   ] Starting outermost env (env.py:286)
2025-05-23 16:53:40 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 16:53:40 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x16cd22da0> created (env.py:336)
2025-05-23 16:53:40 [DEBUG   ] Installing FilePath filesystem handler plugin... (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x16cd22da0>. (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x16cd05090> (env.py:308)
2025-05-23 16:53:40 [DEBUG   ] Entering env context: <rasterio.env.Env object at 0x16cd20160> (env.py:284)
2025-05-23 16:53:40 [DEBUG   ] Got a copy of environment <rasterio._env.GDALEnv object at 0x16cd22da0> options (env.py:346)
2025-05-23 16:53:40 [DEBUG   ] Entered env context: <rasterio.env.Env object at 0x16cd20160> (env.py:308)
2025-05-23 16:53:40 [DEBUG   ] Nodata success: 0, Nodata value: 0.000000 (features.py:392)
2025-05-23 16:53:40 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x16cd20160> (env.py:312)
2025-05-23 16:53:40 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x16cd22da0> options (env.py:373)
2025-05-23 16:53:40 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x16cd22da0>. (env.py:374)
2025-05-23 16:53:40 [DEBUG   ] No GDAL environment exists (env.py:333)
2025-05-23 16:53:40 [DEBUG   ] New GDAL environment <rasterio._env.GDALEnv object at 0x16cd22da0> created (env.py:336)
2025-05-23 16:53:40 [DEBUG   ] GDAL data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/gdal_data'. (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] PROJ data found in package: path='/opt/anaconda3/envs/ldndc/lib/python3.10/site-packages/rasterio/proj_data'. (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x16cd22da0>. (env.py:338)
2025-05-23 16:53:40 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x16cd20160> (env.py:325)
2025-05-23 16:53:40 [DEBUG   ] Exiting env context: <rasterio.env.Env object at 0x16cd05090> (env.py:312)
2025-05-23 16:53:40 [DEBUG   ] Cleared existing <rasterio._env.GDALEnv object at 0x16cd22da0> options (env.py:373)
2025-05-23 16:53:40 [DEBUG   ] Stopped GDALEnv <rasterio._env.GDALEnv object at 0x16cd22da0>. (env.py:374)
2025-05-23 16:53:40 [DEBUG   ] Exiting outermost env (env.py:318)
2025-05-23 16:53:40 [DEBUG   ] Exited env context: <rasterio.env.Env object at 0x16cd05090> (env.py:325)
